### ISSUE TITLE
msj_api_access doesn't support XWalkCordovaView ?

### ISSUE THREAD

**Issue by mattwoberts** [manifoldjs/ManifoldJS#187]
Just trying out the new bits to inject scripts and use cordova APIs, and I get this error:

```
11-26 11:20:07.463  13468-13468/net.azurewebsites.mytestE/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: net.azurewebsites.test, PID: 13468
    java.lang.ClassCastException: org.crosswalk.engine.XWalkCordovaView cannot be cast to org.apache.cordova.engine.SystemWebView
            at com.manifoldjs.hostedwebapp.HostedWebApp$7$1.run(HostedWebApp.java:543)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5272)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
```
Does this mean the new script injection bits aren't going to support XWalkCordovaView, or is this a WIP?

Thanks

**Comment by msrodri** [comment]
Thanks for reporting this is, should be fixed now. You can try the fix by installing the plugin again from v0.2.0 branch (need to uninstall if already installed):

```
cordova plugin add https://github.com/manifoldjs/ManifoldCordova.git#v0.2.0
```

**Comment by mattwoberts** [comment]
Hi - Can't pull the latest version - if I `cordova plugin remove cordova-plugin-hostedwebapp` and then re-add as you suggest, I am still getting the older code (with the cast to a SystemWebView ....

**Comment by f2bo** [comment]
Hi Matt,

Sorry about that. I'm not exactly sure why this happened. In any case, the latest code is already live, so you should be able to add the plugin directly from npm.

```
cordova plugin remove cordova-plugin-hostedwebapp
cordova plugin add cordova-plugin-hostedwebapp
```
